# Training TORA

defaults:
  - model: tora
  - data: main/bbad_everyday
  - trainer: main
  - loggers: wandb
  - _self_

# Random seed for reproducibility
seed: 42

# Data root
data_root: "../dataset"

# Experiment name and log directory
experiment_name: TORA_base
log_dir: ./output/${experiment_name}
ckpt_path: ${log_dir}/last.ckpt
hydra:
  run:
    dir: ${log_dir}

# Model settings
model:
  encoder_ckpt: null
  flow_model_ckpt: null
